spring.application.name=geolocalizacion

# Puerto del microservicio
server.port=8083

# Conexión a PostgreSQL (base de datos NORMAL, sin PostGIS)
spring.datasource.url=jdbc:postgresql://localhost:5432/sanos_salvos_geolocalizacion
spring.datasource.username=postgres
spring.datasource.password=1234

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false