# Puerto independiente para este microservicio
server.port=8082

# Conexión a Base de Datos PostgreSQL (Apunta a la base de datos principal)
spring.datasource.url=jdbc:postgresql://localhost:5432/sanos_salvos_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Configuración de JPA/Hibernate y PostGIS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
